name: CodSpeed

on:
  push:
    branches:
      - "main" # or "master"
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: codspeed-macro-staging
    env:
      CODSPEED_LOG: debug
      CODSPEED_USE_PERF: 1
      CODSPEED_RUNNER_MODE: "walltime"
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "backend/pyproject.toml"

      - name: Install dependencies
        run: uv sync --all-extras --dev
        working-directory: backend

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v3
        env:
          CODSPEED_LOG: debug
          CODSPEED_USE_PERF: true
        with:
          working-directory: backend
          run: uv run pytest --codspeed -k test_create_item
          token: ${{ secrets.CODSPEED_TOKEN }}
          runner-version: 3.6.0
          upload-url: https://api.staging.preview.codspeed.io/upload
